"""add dify_logs and error tables

Revision ID: 2025_08_16_0000
Revises: fa8b0fa6f407
Create Date: 2025-08-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2025_08_16_0000'
down_revision = 'fa8b0fa6f407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dify_logs',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column('app_id', sa.String(255), nullable=True),
        sa.Column('conversation_id', sa.String(255), nullable=True),
        sa.Column('user_id', sa.String(255), nullable=True),
        sa.Column('input_text', sa.Text(), nullable=True),
        sa.Column('output_text', sa.Text(), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('status_code', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, default=sa.func.current_timestamp()),
        sa.Column('dialog_count', sa.Numeric(), nullable=True),
        sa.Column('work_run_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('template', sa.Text(), nullable=True),
        sa.Column('Bot', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='dify_logs_duplicate_pkey')
    )
    
    op.create_table(
        'error',
        sa.Column('id', sa.BigInteger(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column('type_error', sa.String(), nullable=True),
        sa.Column('node', sa.String(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(255), nullable=True),  # Thêm user_id để tracking
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint('id', name='error_pkey')
    )
    
    # Add indexes for better performance
    op.create_index('idx_dify_logs_user_id', 'dify_logs', ['user_id'])
    op.create_index('idx_dify_logs_app_id', 'dify_logs', ['app_id'])
    op.create_index('idx_dify_logs_conversation_id', 'dify_logs', ['conversation_id'])
    op.create_index('idx_dify_logs_created_at', 'dify_logs', ['created_at'])
    
    op.create_index('idx_error_user_id', 'error', ['user_id'])
    op.create_index('idx_error_created_at', 'error', ['created_at'])
    op.create_index('idx_error_type_error', 'error', ['type_error'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_error_type_error', table_name='error')
    op.drop_index('idx_error_created_at', table_name='error')
    op.drop_index('idx_error_user_id', table_name='error')
    
    op.drop_index('idx_dify_logs_created_at', table_name='dify_logs')
    op.drop_index('idx_dify_logs_conversation_id', table_name='dify_logs')
    op.drop_index('idx_dify_logs_app_id', table_name='dify_logs')
    op.drop_index('idx_dify_logs_user_id', table_name='dify_logs')
    
    op.drop_table('error')
    op.drop_table('dify_logs')
    # ### end Alembic commands ###
